from .utilitiesVal import ALLOWED_IMAGE_EXTENSIONS

from .globalVal import SECRET_KEY,\
      ALGORITHM,\
      ACCESS_TOKEN_EXPIRE,\
      ROOT_RESOURCE_PATH,\
      ACCOUNT_RESOURCE_PATH,\
      HEADER_IMAGE_NAME,\
      IMAGE_RESOURCE_PATH,\
      VIDEO_RESOURCE_PATH,\
      RICH_TEXT_RESOURCE_PATH,\
      RICH_TEXT_QUOTE_PATH,\
      ALLOWED_IMAGE_EXTENSIONS,\
      ALLOWED_VIDEO_EXTENSIONS

from .database import database